backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - name: "romanian"
    label: "Pagini Romana"
    folder: "content/romanian"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'english'
    label: 'Pagini Engleza'
    folder: 'content/english'
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'blog_ro'
    label: 'Blog Romana'
    folder: 'content/romanian/blog'
    create: true
    #slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'blog_en'
    label: 'Blog Engleza'
    folder: 'content/english/blog'
    create: true
    #slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'event_ro'
    label: 'Evenimente Romana'
    folder: 'content/romanian/event'
    create: true
    #slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titlu', name: 'title', widget: 'string' }
      - { label: 'Data Publicare', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Imagine Bg', name: 'bgImage', widget: 'image' }
      - { label: 'Imagine', name: 'image', widget: 'image' }
      - { label: 'Data Eveniment', name: 'date', widget: 'datetime' }
      - { label: 'Locatie', name: 'location', widget: 'string',default: 'str. Constantin Esarcu, nr.1' }
      - { label: 'Organizator', name: 'organizer', widget: 'string',default: 'Galeria Rotenberg-Uzunov' }
      - { label: 'Tip', name: 'type', widget: 'string',default: 'event' }
      - { label: 'Categorie', name: 'categ', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'event_en'
    label: 'Evenimente Engleza'
    folder: 'content/english/event'
    create: true
    #slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titlu', name: 'title', widget: 'string' }
      - { label: 'Data Publicare', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Imagine Bg', name: 'bgImage', widget: 'image' }
      - { label: 'Imagine', name: 'image', widget: 'image' }
      - { label: 'Data Eveniment', name: 'date', widget: 'datetime' }
      - { label: 'Locatie', name: 'location', widget: 'string',default: 'str. Constantin Esarcu, nr.1' }
      - { label: 'Organizator', name: 'organizer', widget: 'string',default: 'Galeria Rotenberg-Uzunov' }
      - { label: 'Tip', name: 'type', widget: 'string',default: 'event' }
      - { label: 'Categorie', name: 'categ', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }


#---
#title: "Cadou de principesă: tablouri unicat pentru camera mezinei Principelui Nicolae"
#date: 2020-09-25T11:28:32+06:00
#draft: false
#description : "this is a meta description"
#bgImage: "images/bg/bg-3.jpg"
#image: "images/about/IMG_7362.jpg"
#eventDate: "23 decembrie 2020"
#location: "str. Constantin Esarcu, nr.1"
#organizer: "Galeria Rotenberg-Uzunov"
#type: "event"
#categ : "past"
#---
