backend:
  name: "git-gateway"
  repo: "raduflorin74/asaf_test11"
  branch: "main"
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: 'blog_ro'
    label: 'Blog Romana'
    folder: 'content/romanian/blog'
    create: true
    editor:
      preview: true
    fields:
      - { label: 'Titlu', name: 'title', widget: 'string' }
      - { label: 'Data Publicare', name: 'date', widget: 'datetime' }
      - { label: 'Descriere', name: 'description', widget: 'string' }
      - { label: 'Imagine Bg', name: 'bgImage', widget: 'image' }
      - { label: 'Imagine', name: 'image', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list',default: ['new'] }
      - { label: 'Tip', name: 'type', widget: 'string',default: 'post' }
      - { label: 'Continut', name: 'body', widget: 'markdown' }
  - name: 'blog_en'
    label: 'Blog Engleza'
    folder: 'content/english/blog'
    create: true
    editor:
      preview: true
    fields:
      - { label: 'Titlu', name: 'title', widget: 'string' }
      - { label: 'Data Publicare', name: 'date', widget: 'datetime' }
      - { label: 'Descriere', name: 'description', widget: 'string' }
      - { label: 'Imagine Bg', name: 'bgImage', widget: 'image' }
      - { label: 'Imagine', name: 'image', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list',default: ['new'] }
      - { label: 'Tip', name: 'type', widget: 'string',default: 'post' }
      - { label: 'Continut', name: 'body', widget: 'markdown' }
  - name: 'event_ro'
    label: 'Evenimente Romana'
    folder: 'content/romanian/event'
    create: true
    editor:
      preview: true
    fields:
      - { label: 'Titlu', name: 'title', widget: 'string' }
      - { label: 'Data Publicare', name: 'date', widget: 'datetime' }
      - { label: 'Descriere', name: 'description', widget: 'string' }
      - { label: 'Imagine Bg', name: 'bgImage', widget: 'image' }
      - { label: 'Imagine', name: 'image', widget: 'image' }
      - { label: 'Data Eveniment', name: 'eventDate', widget: 'datetime' }
      - { label: 'Locatie', name: 'location', widget: 'string',default: 'str. Constantin Esarcu, nr.1' }
      - { label: 'Organizator', name: 'organizer', widget: 'string',default: 'Galeria Rotenberg-Uzunov' }
      - { label: 'Tip', name: 'type', widget: 'string',default: 'event' }
      - { label: 'Categorie', name: 'categ', widget: 'list', default: ["past","present","future"] }
      - { label: 'Continut', name: 'body', widget: 'markdown' }
  - name: 'event_en'
    label: 'Evenimente Engleza'
    folder: 'content/english/event'
    create: true
    editor:
      preview: true
    fields:
      - { label: 'Titlu', name: 'title', widget: 'string' }
      - { label: 'Data Publicare', name: 'date', widget: 'datetime' }
      - { label: 'Descriere', name: 'description', widget: 'string' }
      - { label: 'Imagine Bg', name: 'bgImage', widget: 'image' }
      - { label: 'Imagine', name: 'image', widget: 'image' }
      - { label: 'Data Eveniment', name: 'eventDate', widget: 'datetime' }
      - { label: 'Locatie', name: 'location', widget: 'string',default: 'str. Constantin Esarcu, nr.1' }
      - { label: 'Organizator', name: 'organizer', widget: 'string',default: 'Galeria Rotenberg-Uzunov' }
      - { label: 'Tip', name: 'type', widget: 'string',default: 'event' }
      - { label: 'Categorie', name: 'categ', widget: 'list', default: ["past","present","future"] }
      - { label: 'Continut', name: 'body', widget: 'markdown' }
  - name: "settings"
    label: "Settings"
    files:
      - label: "Gallery"
        name: "Gallery"
        file: "data/ro/gallery.yml"
        widget: "list"
        allow_add: true
        summary: '{{fields.image}}'
        fields:
          - { label: 'Imagine', name: 'Image', widget: 'image' }
  - name: "galleria"
    label: "galleria"
    folder: 'content/romanian/gallery' 
    widget: "list"
    optional: true
    fields:
      - {label: "Title", name: "imgTitle", widget: "string"}
      - {label: "Gallery Image", name: "imgSrc", widget: "image"}
      - {label: "Description", name: "imgDesc", widget: "string"}
